server {
    listen 80 default_server;
    server_name _;
    access_log /var/log/nginx/access.log experimento_csv;
    location /videos/ {
        alias /var/www/media/;
        mp4;
        mp4_buffer_size       1m;
        mp4_max_buffer_size   10m;
        mp4_start_key_frame   on;
	send_timeout 500s;
	limit_rate 125k;
	keepalive_timeout 500s;
    }
}
